@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2NDczOTE0MTh9.fm25g4AmhVkdr2hQztto5fKqUXw1kYZJXNP4ZrzxF5s

### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Test name",
  "email": "tabish@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "tabish@test.com",
  "password": "password"
}

### user_cryptos create
POST http://localhost:3000/user_cryptos
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "symbol": "ETHBTC",
  "name": "Etherium",
  "price": 1000,
  "quantity": 5
}

### user_cryptos index
GET http://localhost:3000/user_cryptos
Content-Type: application/json
Authorization: Bearer {{jwt}}

### cryptos index
patch http://localhost:3000/user_cryptos/6
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "quantity": 5
}

### user_cryptos destroy
delete http://localhost:3000/user_cryptos/6
Content-Type: application/json
Authorization: Bearer {{jwt}}

